CREATE TABLE book (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '图书ID',
    title VARCHAR(255) NOT NULL COMMENT '书名',
    author VARCHAR(255) NOT NULL COMMENT '作者',
    cover_image VARCHAR(500) DEFAULT NULL COMMENT '封面图片路径',
    description TEXT COMMENT '简介',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图书表';